### ISSUE TITLE
Question: Unable to get the plugin to work, missing steps?

### ISSUE THREAD

**Issue by lkrell** [simologos/docusaurus-plugin-includes#1]
My team would love to use this plugin, but we have yet to get it to work with Docusaurus. We tried it with versions from the dependency version (.72) through to Beta.  We have it added via yarn, in package.json, configured using your code/instructions from the readme, and building without errors. But all {@include filelocation/filename.md} and variable entries are generating as plain text. 

Files are not being embedded, placeholders are not replacing.

Is there a specific import line to include in the markdown files? Additional configurations to take? Do you have an example demo working with it somewhere? Thanks!

**Comment by simologos** [comment]
Hi there! Do you have a repo somewhere where we can check?
The demos we have available are all internal. But if you have a repo somewhere we're happy to take it from there :-)

**Comment by lkrell** [comment]
Thank you so much for the offered help! We switched to MDX embeds, but would much rather use your plugin. It looks like it has everything we would need and love to have.

I bet I have a simple configuration issue, just can't find it. I appreciate your looking through the files! 

I have a [branch](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/tree/plugin-test-includes) I am working out of testing the plugin again with some variables and shared files (shared are in /docs and /versioned_docs, just trying to get them to work in /docs right now). 

Here are the files:

- [package.json](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/plugin-test-includes/package.json#L31) entry line.
- [docusaurus.config.js](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/plugin-test-includes/docusaurus.config.js#L567-L586) lines for the plugin
- [One of the shared folders](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/tree/plugin-test-includes/docs/shared) has files following MDX embed naming standards and a plain test.md. Tried both, neither are pulled.
- [Markdown file](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/plugin-test-includes/docs/tutorials/helloworldintro.md) with the includes for variables and files that I'm testing. 

I tried many different file names, locations, formats for the variable (which would be nice in the readme), and file include (tried a few options, none work). I tried to trigger an error from your plugin, but it didn't error. So get a feeling the plugin is simply not running correctly?

Thank you!

**Comment by techfreak01** [comment]
Hi

I checked out your branch `plugin-test-includes`, then executed `yarn install`and then `yarn start`.

Here (on a Windows PC) the (4th) include statement `{@include: ../shared/test.md}` in `helloworldintro.md` is successfully replaced with the content of the file `test.md` and also `{BossRoom}` is replaced with the configured text.
The other include statements are replaced with "Include file not found: ..." and the path where it was expected.
Your configuration seems to be correct.
See screenshot from browser below:

![grafik](https://user-images.githubusercontent.com/46628861/121497867-27a45000-c9dc-11eb-8bdf-7383b9be4665.png)

If you see just the placeholders as plain text instead of the replacements, it seems that the plugin is not really loaded and executed.

**Comment by lkrell** [comment]
Hmmmm interesting. Yeah I'm on Mac and it never replaces when local. So strange. I'll try pushing to a sandbox server and see what happens! :) Thank you for double checking. It's a huge relief to know it works, just maybe not locally.

**Comment by lkrell** [comment]
Tried building to a sandbox server, the plugin never initiates. Continuing to investigate. It seems to never initiate on unix systems (mac os, our build servers). Not sure what is completely blocking it. Checking file permissions.

**Comment by techfreak01** [comment]
I could reproduce the issue now on a Mac. The code used windows specific path separators \ in some places.
I fixed that and it should now also work on Mac/Linux/Unix systems.

Please try the updated package release 1.1.1.

Regards, Matthias
