### ISSUE TITLE
Plugin not working in combination with plugin-content-docs?

### ISSUE THREAD

**Issue by Dr-Electron** [simologos/docusaurus-plugin-includes#2]
Hi,
great plugin, but somehow I can't get it to work in combination with the content-docs plugin.
Our repo has a default docs directory and on build it fetches docs from other repos (which get added to the `external` directory).
This plugin only works for the documentation passed to the docs object in the classic preset but not with the docs in the content-docs plugin. They should be the same, right? Or did I misunderstand something?

In this config the include plugin works for the default docs:
```
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          id: "docs",
          sidebarPath: require.resolve('./sidebars.js'),
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ]
  ],
  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'doc2',
        path: 'external/docs2/docs',
        routeBasePath: 'docs2',
        sidebarPath: require.resolve('./external/doc2/sidebars.js'),
      }
    ],
  ]
```

But if I simply replace the docs it works for the docs2:
```
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
           id: 'doc2',
           path: 'external/docs2/docs',
           routeBasePath: 'docs2',
           sidebarPath: require.resolve('./external/doc2/sidebars.js'),
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ]
  ],
  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        id: "docs",
        sidebarPath: require.resolve('./sidebars.js'),
      }
    ],
  ]
```

Thanks for your help in advance

**Comment by techfreak01** [comment]
Hi

If I understand your request correctly, you have 2 instances of plugin-content-docs, one loaded from preset-classic (=docs in preset-classic) and another one with another docs folder added on plugins config section?

This is unfortunately not supported by current version of docusaurus-plugin-includes.
The plugin docusaurus-plugin-includes only works with one instance of docusaurus-plugin-docs.

At runtime, docusaurus-plugin-includes is searching for the instance of docusaurus-plugin-docs, then copies the list of files handled by that instance of docusaurus-plugin-docs, and finally adds a WebPack rule to process these files with an additional loader from within docusaurus-plugin-includes (you can find that in the sourcecode in index.ts, configureWebpack).

Regards,
techfreak01
